# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
prompts:
  - task: content_safety_check_input $model=content_safety
    messages:
      - type: user
        content: "{{ user_input }}"
    output_parser: nemotron_content_safety_parse_prompt_safety
    max_tokens: 100
    max_length: 128000
