# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Cross-engine decision baseline for the four rails IORails ships today.

Every case runs one config and one model payload through **both** engines and asserts
they reach the same allow/block decision. LLMRails goes config -> Colang flow ->
library action; IORails goes config -> RailsManager -> RailAction. Same input, same
verdict, two entirely separate implementations.

**Recorded against ``RailAction``, deliberately, before ``CompiledRail`` exists.**
That ordering is the whole value of the file. These expectations are generated by the
engine being replaced, so the replacement has to satisfy a table it did not author. A
baseline captured after the migration would assert only that the new code equals
itself.

This complements ``tests/test_runtime_flow_gate_equivalence.py`` rather than
duplicating it. That suite stubs the action and pins how a *flow* interprets a
``RailOutcome``; it would stay green through a completely rewritten content-safety
rail. These cases mock at the transport boundary instead, so the real action, the real
prompt rendering, and the real parser all execute — which is what catches a rail whose
meaning changed.

Parity turned out to be stronger than expected: the engines also agree on the
user-visible refusal text, despite reaching it by unrelated routes — IORails from the
``REFUSAL_MESSAGE`` constant, LLMRails from the ``bot refuse to respond`` message in each
rail's ``flows.v1.co``. That literal is duplicated by hand across roughly ten files with
nothing binding them together, so ``test_refusal_text_matches_across_engines`` is the
only thing holding them in agreement. Worth a follow-up issue to give the string one
home; out of scope for this stack.
"""

import copy
from dataclasses import dataclass
from typing import Optional
from unittest.mock import AsyncMock, patch

import pytest

from nemoguardrails.guardrails.iorails import REFUSAL_MESSAGE, IORails
from nemoguardrails.guardrails.model_engine import ModelEngine
from nemoguardrails.rails.llm.config import RailsConfig
from nemoguardrails.types import LLMResponse
from tests.guardrails.test_data import (
    CONTENT_SAFETY_INPUT_PROMPT,
    CONTENT_SAFETY_OUTPUT_PROMPT,
    NEMOGUARDS_CONFIG,
    TOPIC_SAFETY_INPUT_PROMPT,
)
from tests.utils import FakeLLMModel, TestChat

USER_INPUT = "hello there"
MAIN_OUTPUT = "Hello! How can I help?"

SAFE_INPUT_JSON = '{"User Safety": "safe"}'
UNSAFE_INPUT_JSON = '{"User Safety": "unsafe", "Safety Categories": "S1: Violence"}'
SAFE_OUTPUT_JSON = '{"User Safety": "safe", "Response Safety": "safe"}'
UNSAFE_OUTPUT_JSON = '{"User Safety": "safe", "Response Safety": "unsafe", "Safety Categories": "S1: Violence"}'

ON_TOPIC = "on-topic"
OFF_TOPIC = "off-topic"

JAILBREAK_CONFIG = NEMOGUARDS_CONFIG["rails"]["config"]["jailbreak_detection"]
JAILBREAK_URL = JAILBREAK_CONFIG["nim_base_url"].rstrip("/") + JAILBREAK_CONFIG["nim_server_endpoint"]


@dataclass(frozen=True)
class ModelRailCase:
    """One model-backed rail driven to one verdict, expressed as the model's raw reply."""

    case_id: str
    flow: str
    direction: str
    model_type: str
    prompt_task: str
    prompt_content: str
    output_parser: Optional[str]
    rail_reply: str
    expect_blocked: bool


def _model_rail_cases() -> list[ModelRailCase]:
    """Build the safe and blocked case for each of the three model-backed rails."""
    specs = [
        (
            "content_safety_input",
            "content safety check input $model=content_safety",
            "input",
            "content_safety",
            "content_safety_check_input $model=content_safety",
            CONTENT_SAFETY_INPUT_PROMPT,
            "nemoguard_parse_prompt_safety",
            SAFE_INPUT_JSON,
            UNSAFE_INPUT_JSON,
        ),
        (
            "content_safety_output",
            "content safety check output $model=content_safety",
            "output",
            "content_safety",
            "content_safety_check_output $model=content_safety",
            CONTENT_SAFETY_OUTPUT_PROMPT,
            "nemoguard_parse_response_safety",
            SAFE_OUTPUT_JSON,
            UNSAFE_OUTPUT_JSON,
        ),
        (
            "topic_safety_input",
            "topic safety check input $model=topic_control",
            "input",
            "topic_control",
            "topic_safety_check_input $model=topic_control",
            TOPIC_SAFETY_INPUT_PROMPT,
            None,
            ON_TOPIC,
            OFF_TOPIC,
        ),
    ]

    cases = []
    for name, flow, direction, model_type, task, content, parser, allow_reply, block_reply in specs:
        for suffix, reply, blocked in (("allows", allow_reply, False), ("blocks", block_reply, True)):
            cases.append(
                ModelRailCase(
                    case_id=f"{name}_{suffix}",
                    flow=flow,
                    direction=direction,
                    model_type=model_type,
                    prompt_task=task,
                    prompt_content=content,
                    output_parser=parser,
                    rail_reply=reply,
                    expect_blocked=blocked,
                )
            )
    return cases


MODEL_RAIL_CASES = _model_rail_cases()


def _model_rail_config(case: ModelRailCase) -> dict:
    """Build the single-rail config both engines are given for *case*."""
    rail_model = next(model for model in NEMOGUARDS_CONFIG["models"] if model["type"] == case.model_type)
    prompt: dict = {"task": case.prompt_task, "content": case.prompt_content}
    if case.output_parser:
        prompt["output_parser"] = case.output_parser
        prompt["max_tokens"] = 50

    return {
        "models": [copy.deepcopy(NEMOGUARDS_CONFIG["models"][0]), copy.deepcopy(rail_model)],
        "rails": {case.direction: {"flows": [case.flow]}},
        "prompts": [prompt],
    }


def _jailbreak_config() -> dict:
    """Build the jailbreak-only config both engines are given."""
    return {
        "models": [copy.deepcopy(NEMOGUARDS_CONFIG["models"][0])],
        "rails": {
            "input": {"flows": ["jailbreak detection model"]},
            "config": {"jailbreak_detection": copy.deepcopy(JAILBREAK_CONFIG)},
        },
    }


def _assistant_content(response: object) -> str:
    """Return the assistant message content from a ``generate_async`` result.

    Both engines return a plain message dict when called without ``options``; this pins
    that so an accidental ``GenerationResponse`` shows up here rather than as a confusing
    comparison failure downstream.
    """
    assert isinstance(response, dict), f"expected a message dict, got {type(response).__name__}"
    return response["content"]


async def _llmrails_reply(config_dict: dict, rail_model: Optional[tuple[str, str]] = None) -> str:
    """Run one turn through LLMRails and return the assistant content.

    *rail_model* is a ``(model_type, reply)`` pair for rails that call a model, or ``None``
    for rails that do not. It is supplied through ``registered_action_params["llms"]``,
    which is how the Colang runtime hands a named model to a library action; the main model
    comes from ``TestChat``.
    """
    config = RailsConfig.from_content(config=config_dict)
    chat = TestChat(config, llm_completions=[MAIN_OUTPUT])
    if rail_model is not None:
        model_type, reply = rail_model
        chat.app.runtime.registered_action_params["llms"] = {model_type: FakeLLMModel(responses=[reply])}

    response = await chat.app.generate_async(messages=[{"role": "user", "content": USER_INPUT}])
    return _assistant_content(response)


async def _iorails_reply(config_dict: dict, rail_reply: Optional[str] = None) -> str:
    """Run one turn through IORails and return the assistant content.

    Mocks each registered engine's transport so the whole RailsManager -> RailAction ->
    EngineRegistry chain executes without a network call. Rails are keyed by engine name
    rather than model type here, because that is how ``EngineRegistry`` holds them.
    """
    with patch.dict("os.environ", {"NVIDIA_API_KEY": "test-key"}):
        iorails = IORails(RailsConfig.from_content(config=config_dict))

    async with iorails:
        for name, engine in iorails.engine_registry._engines.items():
            if not isinstance(engine, ModelEngine):
                continue
            if name == "main":
                engine.chat_completion = AsyncMock(return_value=LLMResponse(content=MAIN_OUTPUT))
            elif rail_reply is not None:
                engine.chat_completion = AsyncMock(return_value=LLMResponse(content=rail_reply))

        response = await iorails.generate_async(messages=[{"role": "user", "content": USER_INPUT}])
        return _assistant_content(response)


class TestModelBackedRailsAgreeAcrossEngines:
    """The three model-backed rails reach the same decision on both engines."""

    @pytest.mark.asyncio
    @pytest.mark.parametrize("case", MODEL_RAIL_CASES, ids=[case.case_id for case in MODEL_RAIL_CASES])
    async def test_engines_reach_the_same_decision(self, case: ModelRailCase):
        """One model reply drives both engines to the same allow-or-block outcome."""
        config_dict = _model_rail_config(case)

        llmrails_content = await _llmrails_reply(config_dict, (case.model_type, case.rail_reply))
        iorails_content = await _iorails_reply(config_dict, case.rail_reply)

        llmrails_blocked = llmrails_content != MAIN_OUTPUT
        iorails_blocked = iorails_content != MAIN_OUTPUT

        assert llmrails_blocked is case.expect_blocked
        assert iorails_blocked is case.expect_blocked

    @pytest.mark.asyncio
    async def test_refusal_text_matches_across_engines(self):
        """A blocked request renders the same user-visible refusal on both engines.

        The two engines reach this string by unrelated routes: IORails returns the
        ``REFUSAL_MESSAGE`` constant (``iorails.py:94``) and LLMRails renders the
        ``bot refuse to respond`` message defined per rail in ``flows.v1.co``. Nothing in
        the codebase binds those together — the literal is repeated by hand in roughly ten
        files — so this is the only assertion that a user gets the same answer either way.
        """
        case = next(c for c in MODEL_RAIL_CASES if c.case_id == "content_safety_input_blocks")
        config_dict = _model_rail_config(case)

        llmrails_content = await _llmrails_reply(config_dict, (case.model_type, case.rail_reply))
        iorails_content = await _iorails_reply(config_dict, case.rail_reply)

        assert iorails_content == REFUSAL_MESSAGE
        assert llmrails_content == REFUSAL_MESSAGE


class TestJailbreakAgreesAcrossEngines:
    """Jailbreak detection reaches the same decision despite two different transports.

    The engines do not share a transport before the migration: LLMRails calls the NIM over
    httpx from the library action, IORails over aiohttp through APIEngine. Each is mocked
    at its own boundary with the same verdict payload, so the decision is compared even
    though the wire path is not.
    """

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        ("verdict", "expect_blocked"),
        [
            ({"jailbreak": False, "score": 0.05}, False),
            ({"jailbreak": True, "score": 0.95}, True),
        ],
        ids=["jailbreak_model_allows", "jailbreak_model_blocks"],
    )
    async def test_engines_reach_the_same_decision(self, verdict, expect_blocked, httpx_mock):
        """One NIM verdict drives both engines to the same allow-or-block outcome."""
        config_dict = _jailbreak_config()

        httpx_mock.add_response(url=JAILBREAK_URL, json=verdict)
        llmrails_content = await _llmrails_reply(config_dict)

        with patch(
            "nemoguardrails.guardrails.engine_registry.EngineRegistry.api_call",
            new=AsyncMock(return_value=verdict),
        ):
            iorails_content = await _iorails_reply(config_dict)

        assert (llmrails_content != MAIN_OUTPUT) is expect_blocked
        assert (iorails_content != MAIN_OUTPUT) is expect_blocked

    @pytest.mark.asyncio
    async def test_iorails_fails_closed_when_the_endpoint_errors(self):
        """IORails blocks when the NIM call raises, the behavior PR 3 deliberately reverses.

        The library action swallows every exception and allows, so after the migration this
        same scenario must produce MAIN_OUTPUT. Recorded here as the pre-migration verdict
        so the flip is visible as an intended change rather than an unexplained diff.
        """
        with patch(
            "nemoguardrails.guardrails.engine_registry.EngineRegistry.api_call",
            new=AsyncMock(side_effect=RuntimeError("connection refused")),
        ):
            iorails_content = await _iorails_reply(_jailbreak_config())

        assert iorails_content == REFUSAL_MESSAGE
