from nemoguardrails.llm.providers import register_chat_provider
from tests.integrations.langchain.test_configs.with_custom_chat_model.custom_chat_model import CustomChatModel

register_chat_provider("custom_chat_model", CustomChatModel)
