models:
  - type: main
    engine: openai
    model: deepseek-chat
    mode: chat
    api_key_env_var: DEEPSEEK_API_KEY
    parameters:
      base_url: https://api.deepseek.com
      temperature: 0.0

rails:
  output:
    flows:
      - self check hallucination
      - self check facts

lowest_temperature: 0.0

prompts:
  - task: self_check_hallucination
    content: |-
      You are given a task to identify if the hypothesis is in agreement with the context below.
      You will only use the contents of the context and not rely on external knowledge.
      Answer with yes/no. "context": {{ paragraph }} "hypothesis": {{ statement }} "agreement":
    max_tokens: 64

  - task: self_check_facts
    content: |-
      You are given a task to identify if the main claims in a statement are faithful to the given evidence.
      You will only use the contents of the evidence and not rely on external knowledge.
      Answer with yes/no. "evidence": {{ evidence }} "statement": {{ response }} "faithful":
    max_tokens: 64

