# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the manifest-backed rail installation requirements page."""

import argparse
import shlex
from pathlib import Path
from typing import Iterable, Optional

from packaging.markers import Marker

from nemoguardrails.manifests import RailManifest, all_rail_manifests, build_installation_plan
from nemoguardrails.manifests.installation import InstallationPackage, InstallationResource

DOCUMENT_PATH = (
    Path(__file__).resolve().parents[1]
    / "docs"
    / "configure-rails"
    / "guardrail-catalog"
    / "rail-installation-requirements.mdx"
)


def _description(description: Optional[str]) -> str:
    return f" — {' '.join(description.split())}" if description else ""


def _install_command(packages: Iterable[InstallationPackage]) -> str:
    requirements = []
    for package in packages:
        requirement = package.distribution + (package.version or "")
        if package.marker is not None:
            requirement = f"{requirement}; {Marker(package.marker)}"
        requirements.append(shlex.quote(requirement))
    return "pip install " + " ".join(requirements)


def _render_packages(title: str, packages: tuple[InstallationPackage, ...]) -> list[str]:
    if not packages:
        return []
    lines = [f"**{title}**", ""]
    for package in packages:
        lines.append(f"- `{package.requirement}`{_description(package.description)}")
    lines.extend(("", "```bash", _install_command(packages), "```", ""))
    return lines


def _render_resources(title: str, resources: tuple[InstallationResource, ...]) -> list[str]:
    if not resources:
        return []
    lines = [f"**{title}**", ""]
    for resource in resources:
        qualifier = "required" if resource.required else "optional"
        lines.append(f"- `{resource.name}` ({qualifier}){_description(resource.description)}")
    lines.append("")
    return lines


def _documentation_url(manifest: RailManifest) -> Optional[str]:
    path = manifest.metadata.docs_url
    if path is None or not path.startswith("docs/configure-rails/") or not path.endswith(".mdx"):
        return None
    relative = path.removeprefix("docs/configure-rails/").removesuffix(".mdx")
    return f"/configure-guardrails/{relative}"


def _render_manifest(manifest: RailManifest) -> list[str]:
    display_name = manifest.metadata.display_name or manifest.name
    documentation_url = _documentation_url(manifest)
    heading = f"## {display_name} (`{manifest.name}`)"
    if documentation_url is not None:
        heading = f"## [{display_name}]({documentation_url}) (`{manifest.name}`)"
    lines = [heading, ""]
    plan = build_installation_plan((manifest,))
    required = tuple(package for package in plan.python_packages if package.required)
    optional = tuple(package for package in plan.python_packages if not package.required)
    lines.extend(_render_packages("Required Python packages", required))
    lines.extend(_render_packages("Optional Python packages", optional))
    lines.extend(_render_resources("Environment variables", plan.environment_variables))
    lines.extend(_render_resources("Services", plan.services))
    lines.extend(_render_resources("Models", plan.models))
    if not any((plan.python_packages, plan.environment_variables, plan.services, plan.models)):
        lines.extend(("No additional installation resources are declared.", ""))
    return lines


def render_document(manifests: Iterable[RailManifest]) -> str:
    selected = tuple(sorted(manifests, key=lambda manifest: manifest.name))
    lines = [
        "---",
        "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
        "# SPDX-License-Identifier: Apache-2.0",
        'title: "Rail Installation Requirements"',
        'sidebar-title: "Installation Requirements"',
        'description: "Manifest-generated installation requirements for the built-in guardrail catalog."',
        "content:",
        '  type: "reference"',
        "---",
        "",
        "<!-- Generated by scripts/generate_rail_requirements_docs.py. Do not edit directly. -->",
        "",
        "# Rail Installation Requirements",
        "",
        "This page is generated from the requirements declared by each built-in rail manifest. "
        "Install only the packages required by the rails you use. Package markers are preserved so `pip` can apply "
        "the requirement to compatible Python environments.",
        "",
        "To print requirements for a rail or a complete configuration, use:",
        "",
        "```bash",
        "nemoguardrails rails requirements --rail sensitive_data_detection",
        "nemoguardrails rails requirements --config ./config",
        "```",
        "",
        "The command prints installation guidance but never installs packages. Environment-variable values are never "
        "read or displayed. Models and services can require additional setup; follow the linked catalog page for each rail.",
        "",
    ]
    for manifest in selected:
        lines.extend(_render_manifest(manifest))
    return "\n".join(lines).rstrip() + "\n"


def expected_document() -> str:
    return render_document(all_rail_manifests().values())


def write_document(path: Path = DOCUMENT_PATH) -> None:
    path.write_text(expected_document(), encoding="utf-8")


def document_is_current(path: Path = DOCUMENT_PATH) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected_document()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the generated document is stale.")
    args = parser.parse_args()
    if args.check:
        if not document_is_current():
            raise SystemExit("Rail installation requirements are stale; run make generate-rail-requirements.")
        return
    write_document()


if __name__ == "__main__":
    main()
